services:
  app:
    build: .
    container_name: fimoney_app
    restart: always
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - fimoney_net

  mongo:
    image: mongo:6
    container_name: fimoney_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - fimoney_net

volumes:
  mongodata:

networks:
  fimoney_net:
    driver: bridge
